[build]
  command = "npm run build"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "22.13.1"
  NPM_VERSION = "10.9.2"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"